services:
  kosmos_app:
    image: registry.setilic.com/setilic/kosmos/app:latest
    ports:
      - "3000:3000"

  kosmos_backend:
    image: registry.setilic.com/setilic/kosmos/backend:latest
    ports:
      - "5000:5000"
    environment:
      - "DATABASE_URL='postgresql://kosmos:secret@localhost:5432/kosmos'"
      - "CORS_ORIGIN=https://kosmos.setilic.com"
      - "UPLOAD_LOCATION='./uploads'"
      - "IMAGE_PROCESSING_THREADS=4"
      - "DEFAULT_STORAGE_LIMIT=10737418240"
      - "ALLOW_REGISTER=true"
    volumes:
      - ./uploads:./uploads