services:
  kosmos_db:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=kosmos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kosmos
    ports:
      - "5432:5432"
    volumes:
      - kosmos_db_data:/var/lib/postgresql/data

volumes:
    kosmos_db_data: