// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderModelWithShareInfoDTO = { id: string, user_id: string, folder_name: string, parent_id: string | null, favorite: boolean, color: string | null, created_at: string, updated_at: string, share_uuid: string, share_target_username: string | null, };
