// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderModelDTO } from "./FolderModelDTO";
import type { SimpleDirectoryDTO } from "./SimpleDirectoryDTO";

export type FolderResponse = { folder: FolderModelDTO | null, folders: Array<FolderModelDTO>, structure: Array<SimpleDirectoryDTO> | null, };
