// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShareFileModelDTO } from "./ShareFileModelDTO";
import type { ShareFolderModelDTO } from "./ShareFolderModelDTO";
import type { SimpleDirectoryDTO } from "./SimpleDirectoryDTO";

export type FolderShareData = { folder: ShareFolderModelDTO, folders: Array<ShareFolderModelDTO>, files: Array<ShareFileModelDTO>, structure: Array<SimpleDirectoryDTO>, };
