// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationModelDTO = { id: string, user_id: string, operation_type: number, operation_status: number, result: string | null, started_at: string, ended_at: string | null, updated_at: string, };
