// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasskeyModelDTO = { id: string, user_id: string, name: string, created_at: string, };
