// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ShareFileModelDTO = { id: string, file_name: string, file_size: bigint, file_type: number, mime_type: string, metadata: JsonValue | null, preview_status: number | null, created_at: string, updated_at: string, };
