CREATE TABLE IF NOT EXISTS passkeys
(
    id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name          TEXT        NOT NULL,
    credential_id BYTEA       NOT NULL UNIQUE,
    passkey       JSONB        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
