// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMemberModelDTO } from './ChatMemberModelDTO';
import type { ChatType } from './ChatType';

export type ChatModelDTO = {
  id: string;
  members: Array<ChatMemberModelDTO>;
  name: string;
  description: string | null;
  chat_type: ChatType;
  created_at: string;
  updated_at: string;
  latest_message_at: string | null;
};
