// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatAuthorModelDTO = {
  user_id: string;
  has_avatar: boolean;
  full_name: string | null;
  username: string;
};
