// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatAuthorModelDTO } from "./ChatAuthorModelDTO";

export type ChatMessageModelDTO = { id: string, chat_id: string, author: ChatAuthorModelDTO | null, content: string, parent: ChatMessageModelDTO | null, is_edited: boolean, created_at: string, };
