// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileContactPendingModelDTO } from "./ProfileContactPendingModelDTO";

export type ContactRequestsResponse = { requests_sent: Array<ProfileContactPendingModelDTO>, requests_received: Array<ProfileContactPendingModelDTO>, };
