// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactRequestModelDTO } from "./ContactRequestModelDTO";

export type ContactRequestsResponse = { requests_send: Array<ContactRequestModelDTO>, requests_received: Array<ContactRequestModelDTO>, };
