// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactRequestStatus } from './ContactRequestStatus';

export type ContactRequestModelDTO = {
  user_id: bigint;
  request_user_id: bigint;
  status: ContactRequestStatus;
};
