// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskUsageStats = { active: number, bin: number, total: number, limit: number, };
