// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileModelDTO } from "./FileModelDTO";
import type { FileTypeSumDataDTO } from "./FileTypeSumDataDTO";
import type { UsageSumDataDTO } from "./UsageSumDataDTO";

export type DiskUsageReport = { active_storage: UsageSumDataDTO, bin_storage: UsageSumDataDTO, by_file_type: Array<FileTypeSumDataDTO>, large_files: Array<FileModelDTO>, };
