// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileModelDTO } from "./FileModelDTO";
import type { FolderModelDTO } from "./FolderModelDTO";

export type ExplorerSearchDTO = { files: Array<FileModelDTO>, folders: Array<FolderModelDTO>, };
