// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type FileModelDTO = { id: string, user_id: string, file_name: string, file_size: number, file_type: number, mime_type: string, metadata: JsonValue | null, parent_folder_id: string | null, preview_status: number | null, favorite: boolean, created_at: string, updated_at: string, deleted_at: string | null, };
