// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationModelDTO } from './OperationModelDTO';

export type OperationsUpdate = { content: Array<OperationModelDTO> };
