// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceDeletedChatMessage } from "./PresenceDeletedChatMessage";
import type { PresenceNewChatMessage } from "./PresenceNewChatMessage";
import type { PresenceOperationsUpdate } from "./PresenceOperationsUpdate";
import type { PresenceSocialUpdate } from "./PresenceSocialUpdate";
import type { PresenceUpdatedChatMessage } from "./PresenceUpdatedChatMessage";

export type PresenceAction = { "NewChatMessage": PresenceNewChatMessage } | { "DeletedChatMessage": PresenceDeletedChatMessage } | { "UpdatedChatMessage": PresenceUpdatedChatMessage } | { "SocialUpdate": PresenceSocialUpdate } | { "OperationsUpdate": PresenceOperationsUpdate };
