// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageModelDTO } from './ChatMessageModelDTO';

export type PresenceChatMessage = {
  chat_id: bigint;
  content: ChatMessageModelDTO;
};
