// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageModelDTO } from "./ChatMessageModelDTO";

export type PresenceNewChatMessage = { chat_id: string, content: ChatMessageModelDTO, };
