// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileContactLiteModelDTO = {
  user_id: string;
  username: string;
  full_name: string | null;
};
