// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileModelDTO = { user_id: string, full_name: string | null, email: string | null, phone_number: string | null, website: string | null, bio: string | null, location: string | null, };
