// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactRequestStatus } from "./ContactRequestStatus";

export type ProfileContactPendingModelDTO = { id: string, user_id: string, username: string, full_name: string | null, status: ContactRequestStatus, };
