// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PushSubscriptionModelDTO = { id: string, name: string | null, created_at: string, };
