// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SharedAlbumModelDTO = { id: string, name: string, description: string | null, preview_id: string | null, created_at: string, updated_at: string, };
