// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShareModelDTO = { id: string, uuid: string, user_id: string, file_id: string | null, folder_id: string | null, album_id: string | null, share_type: number, share_target: bigint | null, access_limit: number | null, password: string | null, access_count: number, last_access: string | null, created_at: string, expires_at: string | null, updated_at: string, };
