// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumModelWithShareInfoDTO } from "./AlbumModelWithShareInfoDTO";
import type { FileModelWithShareInfoDTO } from "./FileModelWithShareInfoDTO";
import type { FolderModelWithShareInfoDTO } from "./FolderModelWithShareInfoDTO";

export type SharedItems = { files: Array<FileModelWithShareInfoDTO>, folders: Array<FolderModelWithShareInfoDTO>, albums: Array<AlbumModelWithShareInfoDTO>, };
