// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShareFolderModelDTO = { id: string, folder_name: string, color: string | null, parent_id: string | null, created_at: string, updated_at: string, };
