// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimpleDirectoryDTO = { id: string, folder_name: string, color: string | null, };
