// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserModelDTO = { id: string, username: string, full_name: string | null, email: string | null, storage_limit: number, role: number, created_at: string, updated_at: string, };
